// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAMaCrbgspznOqKa0pSRb51cYLZOIfGfw',
    appId: '1:1090721689537:web:b17323740f1d7e87474940',
    messagingSenderId: '1090721689537',
    projectId: 'mindmentor-bc846',
    authDomain: 'mindmentor-bc846.firebaseapp.com',
    databaseURL: 'https://mindmentor-bc846-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindmentor-bc846.appspot.com',
    measurementId: 'G-23CR49BMPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyL1B_X7UFMHFZUvsGOBRuff3r-YryqUw',
    appId: '1:1090721689537:android:4ce04b71abad7b17474940',
    messagingSenderId: '1090721689537',
    projectId: 'mindmentor-bc846',
    databaseURL: 'https://mindmentor-bc846-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindmentor-bc846.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYVnoQOVf-wVP1OmhMTGey82T_qQd2xb8',
    appId: '1:1090721689537:ios:c722b6b8707c2457474940',
    messagingSenderId: '1090721689537',
    projectId: 'mindmentor-bc846',
    databaseURL: 'https://mindmentor-bc846-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindmentor-bc846.appspot.com',
    iosClientId: '1090721689537-7u32th9l05sv2kpf2ikg576mmkdm4uvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.optima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGVtLkUdQ88S9RNMrHxx53Yzkg6qwnqhw',
    appId: '1:1090721689537:web:1f5c4b2d4634edab474940',
    messagingSenderId: '1090721689537',
    projectId: 'mindmentor-bc846',
    authDomain: 'mindmentor-bc846.firebaseapp.com',
    databaseURL: 'https://mindmentor-bc846-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindmentor-bc846.appspot.com',
    measurementId: 'G-M7VVJE5E1W',
  );

}